spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 2
#      connection-timeout: 2000
#      idle-timeout: 300000
#      max-lifetime: 1200000

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
